package platform

// Code generated by TestAggregateSpeedResults at 2025-11-17 17:47:30; 
// 该文件通过聚合 test_output/speed_results*.csv 生成，用于提供额外精选测速 URL。

var fastSpeedTestURLs = []string{
        "https://updates.cdn-apple.com/2025FallFCS/fullrestores/089-12066/4F86CB11-E6FA-47CB-96A8-527A4CBD9273/iPhone18,3_26.1_23B85_Restore.ipsw", // avg: 8229.89 KB/s, samples: 12, errors: 1
        "https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe", // avg: 6534.46 KB/s, samples: 11, errors: 1
        "http://updates-http.cdn-apple.com/2019WinterFCS/fullrestores/041-39257/32129B6C-292C-11E9-9E72-4511412B0A59/iPhone_4.7_12.1.4_16D57_Restore.ipsw", // avg: 3948.10 KB/s, samples: 11, errors: 2
        "https://speed.cloudflare.com/__down?bytes=1073741824", // avg: 3658.52 KB/s, samples: 11, errors: 1
        "http://sgp.download.datapacket.com/1000mb.bin", // avg: 3593.15 KB/s, samples: 12, errors: 1
        "https://update.code.visualstudio.com/1.102.0/win32-x64-user/stable", // avg: 3297.29 KB/s, samples: 10, errors: 2
        "http://hkg.download.datapacket.com/10000mb.bin", // avg: 3044.69 KB/s, samples: 11, errors: 2
        "https://nodejs.org/dist/v22.13.1/node-v22.13.1-x64.msi", // avg: 2892.90 KB/s, samples: 11, errors: 1
        "http://sgp.download.datapacket.com/100mb.bin", // avg: 2795.06 KB/s, samples: 12, errors: 1
        "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.0-linux-x86_64.tar.gz", // avg: 2743.58 KB/s, samples: 12, errors: 1
        "https://speed.cloudflare.com/__down?bytes=5368709120", // avg: 2645.99 KB/s, samples: 11, errors: 1
        "http://sgp.download.datapacket.com/10000mb.bin", // avg: 2498.18 KB/s, samples: 12, errors: 1
        "http://tyo.download.datapacket.com/100mb.bin", // avg: 2337.63 KB/s, samples: 12, errors: 1
        "http://lax.download.datapacket.com/10000mb.bin", // avg: 2286.95 KB/s, samples: 11, errors: 1
        "https://cachefly.cachefly.net/300mb.test", // avg: 2143.48 KB/s, samples: 9, errors: 3
        "http://lax.download.datapacket.com/100mb.bin", // avg: 2080.53 KB/s, samples: 12, errors: 0
        "http://tyo.download.datapacket.com/10000mb.bin", // avg: 2072.19 KB/s, samples: 11, errors: 1
        "http://lax.download.datapacket.com/1000mb.bin", // avg: 2024.75 KB/s, samples: 12, errors: 0
        "http://ash.download.datapacket.com/10000mb.bin", // avg: 1975.45 KB/s, samples: 11, errors: 2
        "http://ash.download.datapacket.com/100mb.bin", // avg: 1959.89 KB/s, samples: 11, errors: 2
        "https://sgp.proof.ovh.net/files/100Mb.dat", // avg: 1926.47 KB/s, samples: 11, errors: 2
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.42.06_linux.run", // avg: 1877.84 KB/s, samples: 8, errors: 4
        "https://sgp.proof.ovh.net/files/1Gb.dat", // avg: 1826.92 KB/s, samples: 11, errors: 2
        "https://static.rust-lang.org/dist/rust-1.83.0-x86_64-unknown-linux-gnu.tar.gz", // avg: 1791.07 KB/s, samples: 10, errors: 2
        "http://ash.download.datapacket.com/1000mb.bin", // avg: 1757.90 KB/s, samples: 11, errors: 2
        "https://awscli.amazonaws.com/AWSCLIV2.msi", // avg: 1637.59 KB/s, samples: 10, errors: 2
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.85_windows.exe", // avg: 1611.88 KB/s, samples: 9, errors: 4
        "http://hkg.download.datapacket.com/1000mb.bin", // avg: 1610.92 KB/s, samples: 11, errors: 2
        "https://download.blender.org/release/Blender4.3/blender-4.3.0-windows-x64.zip", // avg: 1605.15 KB/s, samples: 12, errors: 1
        "http://tyo.download.datapacket.com/1000mb.bin", // avg: 1444.76 KB/s, samples: 11, errors: 2
        "https://download.blender.org/release/Blender4.3/blender-4.3.0-linux-x64.tar.xz", // avg: 1408.20 KB/s, samples: 11, errors: 1
        "http://par.download.datapacket.com/10000mb.bin", // avg: 1388.68 KB/s, samples: 12, errors: 1
        "https://github.com/pytorch/pytorch/releases/download/v2.9.1/pytorch-v2.9.1.tar.gz", // avg: 1358.06 KB/s, samples: 9, errors: 3
        "http://hkg.download.datapacket.com/100mb.bin", // avg: 1296.48 KB/s, samples: 11, errors: 2
        "http://par.download.datapacket.com/100mb.bin", // avg: 1288.52 KB/s, samples: 12, errors: 1
        "https://gra.proof.ovh.net/files/100Mb.dat", // avg: 1176.72 KB/s, samples: 12, errors: 1
        "https://fra-de-ping.vultr.com/vultr.com.100MB.bin", // avg: 1143.71 KB/s, samples: 11, errors: 2
        "https://lax-ca-us-ping.vultr.com/vultr.com.1000MB.bin", // avg: 1075.04 KB/s, samples: 9, errors: 3
}
