package platform

// Code generated by TestAggregateSpeedResults at 2025-11-19 22:35:53; 
// 该文件通过聚合 test_output/speed_results*.csv 生成，用于提供额外精选测速 URL。

var fastSpeedTestURLs = []string{
        "https://updates.cdn-apple.com/2025FallFCS/fullrestores/089-12066/4F86CB11-E6FA-47CB-96A8-527A4CBD9273/iPhone18,3_26.1_23B85_Restore.ipsw",
        "http://lax.download.datapacket.com/10000mb.bin", 
        "https://nodejs.org/dist/v22.13.1/node-v22.13.1-x64.msi",
        "https://download-installer.cdn.mozilla.net/pub/firefox/releases/145.0/win64/en-US/Firefox%20Setup%20145.0.exe", 
        "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/43.20251024.3.0/x86_64/fedora-coreos-43.20251024.3.0-live-iso.x86_64.iso",
        "https://hil.proof.ovh.us/files/1Gb.dat",
        "https://update.code.visualstudio.com/1.102.0/win32-x64-user/stable",
        "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.0-linux-x86_64.tar.gz", 
        "https://cachefly.cachefly.net/300mb.test", 
        "https://mirror.rackspace.com/archlinux/iso/2025.11.01/archlinux-2025.11.01-x86_64.iso", 
        "https://hnd-jp-ping.vultr.com/vultr.com.100MB.bin",
}
